kind: Deployment
apiVersion: apps/v1
metadata:
  name: acm-quarkus-deployment
  namespace: acm-demo
  labels:
    app: acm-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-quarkus
  template:
    metadata:
      labels:
        app: acm-quarkus
    spec:
      containers:
        - name: quarkus-hello-app
          image: quay.io/naveenkendyala/quarkus-demo-quarkusjvm-hello:v1
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            requests: 
              memory: "100Mi"
              cpu: "200m" 
            limits:
              memory: "100Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/livecheck
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10