apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: acm-quarkus
  name: acm-demo-app 
  namespace: acm-demo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
     matchLabels:
       app: acm-quarkus
