apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: quarkus-hello-app 
  namespace: quarkus-hello-demo
spec:
  selector:
    matchExpressions:
      - key: deployment
        operator: In
        values:
        - quarkus-hello-app
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription