apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: quarkus-hello-app-cluster2
  namespace: quarkus-hello-demo
  labels:
    deployment: quarkus-hello-app
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: clusters/overlays/cluster2
spec:
  channel:  quarkus-hello-demo/quarkus-hello-demo-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster2