apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: racm-poc-dev-sub
  namespace: acm-demo
  labels:
    app: acm-quarkus
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: clusters/overlays/cluster1/
spec:
  channel:  acm-demo/acm-demo-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: racm-poc-dev-pr